include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: ^3.1.0

formatter:
  page_width: 120

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_const_constructors_in_immutables
    - prefer_single_quotes
    - unawaited_futures
    - sort_child_properties_last
    - prefer_final_locals
    - unnecessary_null_checks
    - avoid_redundant_argument_values
    - no_logic_in_create_state
    - constant_identifier_names
